// From yelp category list
const FoodType = [
    { name: 'Afghan', code:  'afghani'},
    { name: 'African', code:  'african'},
    { name: 'American', code:  'tradamerican'},
    { name: 'Arabic', code:  'arabian'},
    { name: 'Argentine', code:  'argentine'},
    { name: 'Asian Fusion', code:  'asianfusion'},
    { name: 'Australian', code:  'australian'},
    { name: 'Austrian', code:  'austrian'},
    { name: 'Bangladeshi', code:  'bangladeshi'},
    { name: 'Barbeque', code:  'bbq'},
    { name: 'Bistros', code:  'bistros'},
    { name: 'Brasseries', code:  'arabian'},
    { name: 'Basque', code:  'basque'},
    { name: 'Brazilian', code:  'brazilian'},
    { name: 'British', code:  'british'},
    { name: 'Buffets', code:  'buffets'},
    { name: 'Burgers', code:  'burgers'},
    { name: 'Burmese', code:  'burmese'},
    { name: 'Cafeteria', code:  'cafeteria'},
    { name: 'Cafes', code:  'cafes'},
    { name: 'Cajun/Creole', code:  'cajun'},
    { name: 'Caribbean', code:  'caribbean'},
    { name: 'Cheesesteaks', code:  'cheesesteaks'},
    { name: 'Chicken Shop', code:  'chickenshop'},
    { name: 'Chicken Wings', code:  'chicken_wings'},
    { name: 'Comfort Food', code:  'comfortfood'},
    { name: 'Creperies', code: 'creperies'},
    { name: 'Delis', code:  'delis'},
    { name: 'Diners', code:  'diners'},
    { name: 'Ethiopian', code:  'ethiopian'},
    { name: 'Fast Food', code:  'hotdogs'},
    { name: 'Filipino', code:  'filipino'},
    { name: 'Fish & Chips', code:  'fishnchips'},
    { name: 'Fondue', code:  'fondue'},
    { name: 'French', code:  'french'},
    { name: 'Comfort Food', code:  'comfortfood'},
    { name: 'Gastropubs', code: 'gastropubs'},
    { name: 'German', code:  'german'},
    { name: 'Greek', code:  'greek'},
    { name: 'Guamanian', code:  'guamanian'},
    { name: 'Hawaiian', code:  'hawaiian'},
    { name: 'Honduran', code:  'honduran'},
    { name: 'Himalayan/Nepalese', code:  'himalayan'},
    { name: 'Hot Dogs', code:  'hotdog'},
    { name: 'Hot Pot', code:  'hotpot'},
    { name: 'Hungarian', code:  'hungarian'},
    { name: 'Indian', code:  'indpak'},
    { name: 'Iberian', code: 'iberian'},
    { name: 'Indonesian', code:  'guamindonesiananian'},
    { name: 'International', code:  'international'},
    { name: 'Irish', code:  'irish'},
    { name: 'Italian', code:  'italian'},
    { name: 'Japanese', code:  'japanese'},
    { name: 'Laotian', code:  'laotian'},
    { name: 'Latin American', code:  'latin'},
    { name: 'Malaysian', code:  'malaysian'},
    { name: 'Mediterranean', code: 'mediterranean'},
    { name: 'Mexican', code:  'mexican'},
    { name: 'Middle Eastern', code:  'mideastern'},
    { name: 'Modern European ', code:  'modern_european'},
    { name: 'Mongolian', code:  'mongolian'},
    { name: 'Moroccan', code:  'moroccan'},
    { name: 'Nicaraguan', code:  'nicaraguan'},
    { name: 'Noodles', code:  'noodles'},
    { name: 'Pan Asian', code:  'panasian'},
    { name: 'Persian/Iranian', code: 'persian'},
    { name: 'Peruvian', code:  'peruvian'},
    { name: 'Pizza', code:  'pizza'},
    { name: 'Polish', code:  'polish'},
    { name: 'Portuguese', code:  'portuguese'},
    { name: 'Poutineries', code:  'poutineries'},
    { name: 'Russian', code:  'russian'},
    { name: 'Salad', code:  'salad'},
    { name: 'Sandwiches', code:  'sandwiches'},
    { name: 'Scandinavian', code: 'scandinavian'},
    { name: 'Scottish', code: 'scottish'},
    { name: 'Seafood', code:  'poseafoodlish'},
    { name: 'Singaporean', code:  'singaporean'},
    { name: 'Soup', code:  'soup'},
    { name: 'Spanish', code:  'spanish'},
    { name: 'Sri Lankan', code:  'srilankan'},
    { name: 'Steakhouses', code:  'steak'},
    { name: 'Sushi Bars', code: 'sushi'},
    { name: 'Syrian', code: 'syrian'},
    { name: 'Taiwanese', code:  'taiwanese'},
    { name: 'Tapas/Small Plates', code:  'tapasmallplates'},
    { name: 'Thai', code:  'thai'},
    { name: 'Tex-Mex', code:  'tex-mex'},
    { name: 'Turkish', code:  'turkish'},
    { name: 'Ukrainian', code:  'ukrainian'},
    { name: 'Vegan', code: 'vegan'},
    { name: 'Vietnamese', code: 'vietnamese'},
]

export default FoodType;